<?php $baseUrl= $this->getBaseUrl(); ?>
<a class="action submit primary" href="<?php echo $baseUrl .'myform/index/index' ?>">
                <span>Add New Employee</span>
</a>
<?php  
$_employeerecords = $this->getCollection(); 
if($_employeerecords && count($_employeerecords))
{
?>
<table>
    <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('ID #') ?></th>
            <th scope="col" class="col title"><?php echo __('Employee Name') ?></th>
            <th scope="col" class="col title"><?php echo __('Employee Address') ?></th>
            <th scope="col" class="col ">&nbsp;</th>
        </tr>
    </thead>
	<?php
		foreach ($_employeerecords as $employee) 
		{
	?>
		<tr>
			<td><?php echo $employee->getData('e_id'); ?></td>
			<td><?php echo $employee->getData('e_name'); ?></td>
			<td><?php echo $employee->getData('e_address'); ?></td>
		</tr>
	<?php
		}
}
?>
</table>
<?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>